/** Stable codes returned to callers and in HTTP JSON for internal service RPC. */

export const InternalInferenceErrorCode = {
  NO_ACTIVE_INTERNAL_HOST_HANDSHAKE: 'NO_ACTIVE_INTERNAL_HOST_HANDSHAKE',
  HOST_DIRECT_P2P_UNAVAILABLE: 'HOST_DIRECT_P2P_UNAVAILABLE',
  INVALID_INTERNAL_ROLE: 'INVALID_INTERNAL_ROLE',
  POLICY_FORBIDDEN: 'POLICY_FORBIDDEN',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  SERVICE_RPC_NOT_SUPPORTED: 'SERVICE_RPC_NOT_SUPPORTED',
  /** Wire / required-field validation (client or inbound). */
  MALFORMED_SERVICE_MESSAGE: 'MALFORMED_SERVICE_MESSAGE',
  /** Host policy: internal inference is off. */
  HOST_INFERENCE_DISABLED: 'HOST_INFERENCE_DISABLED',
  MODEL_UNAVAILABLE: 'MODEL_UNAVAILABLE',
  OLLAMA_UNAVAILABLE: 'OLLAMA_UNAVAILABLE',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  RATE_LIMITED: 'RATE_LIMITED',
  REQUEST_EXPIRED: 'REQUEST_EXPIRED',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  PROVIDER_BUSY: 'PROVIDER_BUSY',
  INTERNAL_INFERENCE_FAILED: 'INTERNAL_INFERENCE_FAILED',
} as const

export type InternalInferenceErrorCodeType =
  (typeof InternalInferenceErrorCode)[keyof typeof InternalInferenceErrorCode]
