// ============================================================================
// WRVault QSO Remap — Selector Strategy
// ============================================================================
//
// Generates robust selectors and DOM signatures for login form elements.
// Prefers stable attributes (name, autocomplete, aria-label, id) over
// brittle CSS classes. Stores a fallback signature for fuzzy re-matching
// when selectors break due to site UI changes.
//
// Security contract:
//   - No DOM writes. Pure read-only analysis.
//   - No PII in stored data beyond field metadata.
//   - Cross-origin iframe elements are rejected.
// ============================================================================

// ============================================================================
// §1  Types
// ============================================================================

/** Stored selector + signature for a single login form element. */
export interface ElementMapping {
  /** Primary selector (stable attributes preferred). */
  selector: string
  /** Fallback signature for fuzzy matching when selector breaks. */
  signature: ElementSignature
  /** Role in the login form. */
  role: 'username' | 'password' | 'submit'
}

/** Structural fingerprint of a DOM element — no CSS classes, no volatile attrs. */
export interface ElementSignature {
  tagName: string
  inputType: string
  inputMode: string
  autocomplete: string
  name: string
  ariaLabel: string
  /** Hash of form action hostname+path (if in a form). Not the full URL. */
  formActionHash: string
  /** Depth from form root (or document.body if no form). */
  formDepth: number
  /** Ordinal index among sibling elements of same tagName in the form. */
  formIndex: number
  /** Placeholder text (first 40 chars). */
  placeholder: string
}

/** Mapping payload for a complete login form (stored in vault item meta). */
export interface LoginFormMapping {
  /** Schema version for forward compatibility. */
  mapping_version: 1
  /** Effective origin: scheme+host+port. */
  origin: string
  /** Mapped elements (username is optional for password-only sites). */
  username?: ElementMapping
  password: ElementMapping
  submit: ElementMapping
  /** ISO timestamp of last successful verification. */
  last_verified_at: string
  /** ISO timestamp of creation. */
  created_at: string
  /** Optional user label. */
  label?: string
}

/** Score result when validating a stored mapping against the live DOM. */
export interface MappingValidationResult {
  valid: boolean
  /** Per-element resolution status. */
  username: ElementResolution | null
  password: ElementResolution
  submit: ElementResolution
  /** Overall confidence 0-100. */
  confidence: number
  /** Specific failure reasons. */
  failures: string[]
}

export interface ElementResolution {
  found: boolean
  element: HTMLElement | null
  /** How the element was found. */
  method: 'selector' | 'signature_fallback' | 'not_found'
  /** Signature match score 0-100. */
  signatureScore: number
}

// ============================================================================
// §2  Selector Generation
// ============================================================================

/** Minimum acceptable signature match score for fallback resolution. */
const SIGNATURE_MATCH_THRESHOLD = 55

/**
 * Build the most stable selector possible for a given element.
 * Preference order: id > name+type > autocomplete > aria-label > CSS path.
 */
export function buildSelector(el: HTMLElement): string {
  const tag = el.tagName.toLowerCase()

  // 1. Unique ID (if it looks stable, not auto-generated)
  if (el.id && !looksAutoGenerated(el.id)) {
    return `#${cssEscape(el.id)}`
  }

  // 2. name + type (very stable for form inputs)
  const name = (el as HTMLInputElement).name
  const type = (el as HTMLInputElement).type?.toLowerCase() ?? ''
  if (name && !looksAutoGenerated(name)) {
    return `${tag}[name="${cssEscape(name)}"]${type ? `[type="${type}"]` : ''}`
  }

  // 3. autocomplete attribute (semantic, stable)
  const ac = el.getAttribute('autocomplete')
  if (ac && ac !== 'off' && ac !== 'on') {
    return `${tag}[autocomplete="${cssEscape(ac)}"]`
  }

  // 4. aria-label
  const ariaLabel = el.getAttribute('aria-label')
  if (ariaLabel && ariaLabel.length > 2 && ariaLabel.length < 80) {
    return `${tag}[aria-label="${cssEscape(ariaLabel)}"]`
  }

  // 5. Fallback: type within form
  if (type) {
    const form = el.closest('form')
    if (form) {
      const siblings = form.querySelectorAll<HTMLElement>(`${tag}[type="${type}"]`)
      const idx = Array.from(siblings).indexOf(el)
      if (idx >= 0 && siblings.length <= 5) {
        return `form ${tag}[type="${type}"]:nth-of-type(${idx + 1})`
      }
    }
  }

  // 6. Last resort: generic tag + index
  return `${tag}`
}

/**
 * Build a structural signature for fuzzy re-matching.
 */
export function buildSignature(el: HTMLElement): ElementSignature {
  const form = el.closest('form') as HTMLFormElement | null

  return {
    tagName: el.tagName,
    inputType: (el as HTMLInputElement).type?.toLowerCase() ?? '',
    inputMode: el.getAttribute('inputmode') ?? '',
    autocomplete: el.getAttribute('autocomplete') ?? '',
    name: (el as HTMLInputElement).name ?? '',
    ariaLabel: el.getAttribute('aria-label') ?? '',
    formActionHash: form?.action ? hashFormAction(form.action) : '',
    formDepth: computeFormDepth(el, form),
    formIndex: computeFormIndex(el, form),
    placeholder: ((el as HTMLInputElement).placeholder ?? '').slice(0, 40),
  }
}

/**
 * Build a complete ElementMapping for a login form element.
 */
export function buildElementMapping(
  el: HTMLElement,
  role: 'username' | 'password' | 'submit',
): ElementMapping {
  return {
    selector: buildSelector(el),
    signature: buildSignature(el),
    role,
  }
}

// ============================================================================
// §3  Mapping Validation
// ============================================================================

/**
 * Validate a stored LoginFormMapping against the live DOM.
 *
 * For each mapped element:
 *   1. Try the stored selector first (exact match).
 *   2. If selector fails, attempt fuzzy signature matching against all
 *      elements of the same tagName in the page.
 *   3. Ensure resolved elements are visible, enabled, same-origin, not in iframe.
 */
export function validateMapping(mapping: LoginFormMapping): MappingValidationResult {
  const failures: string[] = []

  // Verify origin matches
  if (mapping.origin !== effectiveOrigin()) {
    return {
      valid: false,
      username: null,
      password: { found: false, element: null, method: 'not_found', signatureScore: 0 },
      submit: { found: false, element: null, method: 'not_found', signatureScore: 0 },
      confidence: 0,
      failures: ['origin_mismatch'],
    }
  }

  const usernameRes = mapping.username
    ? resolveElement(mapping.username)
    : null
  const passwordRes = resolveElement(mapping.password)
  const submitRes = resolveElement(mapping.submit)

  // Password is mandatory
  if (!passwordRes.found) failures.push('password_not_found')
  // Submit is mandatory
  if (!submitRes.found) failures.push('submit_not_found')
  // Username is optional (password-only sites) but flag if mapping expected it
  if (mapping.username && usernameRes && !usernameRes.found) {
    failures.push('username_not_found')
  }

  // Same-form check: password and submit must be in the same form (or both formless)
  if (passwordRes.element && submitRes.element) {
    const pwForm = passwordRes.element.closest('form')
    const subForm = submitRes.element.closest('form')
    if (pwForm !== subForm) {
      failures.push('cross_form')
    }
  }

  // Visibility + enabled checks
  for (const res of [usernameRes, passwordRes, submitRes]) {
    if (!res || !res.element) continue
    if (!isElementUsable(res.element)) {
      failures.push('element_not_usable')
    }
  }

  // Cross-origin iframe check
  for (const res of [usernameRes, passwordRes, submitRes]) {
    if (!res || !res.element) continue
    if (isInCrossOriginFrame(res.element)) {
      failures.push('cross_origin_iframe')
    }
  }

  // Confidence scoring
  let totalScore = 0
  let count = 0
  for (const res of [usernameRes, passwordRes, submitRes]) {
    if (!res) continue
    count++
    totalScore += res.signatureScore
  }
  const confidence = count > 0 ? Math.round(totalScore / count) : 0

  const valid = failures.length === 0 && passwordRes.found && submitRes.found

  return { valid, username: usernameRes, password: passwordRes, submit: submitRes, confidence, failures }
}

/**
 * Resolve a single ElementMapping against the live DOM.
 */
function resolveElement(mapping: ElementMapping): ElementResolution {
  // 1. Try selector
  try {
    const el = document.querySelector<HTMLElement>(mapping.selector)
    if (el && el.isConnected) {
      const score = scoreSignatureMatch(mapping.signature, buildSignature(el))
      if (score >= SIGNATURE_MATCH_THRESHOLD) {
        return { found: true, element: el, method: 'selector', signatureScore: score }
      }
    }
  } catch {
    // Invalid selector — fall through to signature matching
  }

  // 2. Signature fallback: scan elements of same tagName
  const fallback = findBySignatureFallback(mapping.signature, mapping.role)
  if (fallback) {
    return fallback
  }

  return { found: false, element: null, method: 'not_found', signatureScore: 0 }
}

/**
 * Find an element by fuzzy signature matching when the stored selector fails.
 */
function findBySignatureFallback(
  sig: ElementSignature,
  role: 'username' | 'password' | 'submit',
): ElementResolution | null {
  const tag = sig.tagName.toLowerCase()
  const candidates = document.querySelectorAll<HTMLElement>(tag)

  let bestEl: HTMLElement | null = null
  let bestScore = 0

  // Cap iteration to prevent DoS on large DOMs
  const limit = Math.min(candidates.length, 200)
  for (let i = 0; i < limit; i++) {
    const el = candidates[i]
    if (!el.isConnected || !isElementUsable(el)) continue

    // Quick filter: for inputs, type must roughly match
    if (role === 'password' && (el as HTMLInputElement).type !== 'password') continue
    if (role === 'username') {
      const t = (el as HTMLInputElement).type?.toLowerCase()
      if (t !== 'text' && t !== 'email' && t !== 'tel' && t !== '') continue
    }

    const liveSig = buildSignature(el)
    const score = scoreSignatureMatch(sig, liveSig)
    if (score > bestScore && score >= SIGNATURE_MATCH_THRESHOLD) {
      bestScore = score
      bestEl = el
    }
  }

  if (bestEl) {
    return { found: true, element: bestEl, method: 'signature_fallback', signatureScore: bestScore }
  }
  return null
}

// ============================================================================
// §4  Signature Scoring
// ============================================================================

/**
 * Score how well two signatures match. Returns 0-100.
 * Weighted by attribute stability and specificity.
 */
export function scoreSignatureMatch(stored: ElementSignature, live: ElementSignature): number {
  let score = 0
  let maxScore = 0

  // tagName: must match (hard gate)
  if (stored.tagName !== live.tagName) return 0

  // name (20 pts) — very stable
  maxScore += 20
  if (stored.name && stored.name === live.name) score += 20
  else if (!stored.name && !live.name) score += 10

  // inputType (15 pts) — stable for inputs
  maxScore += 15
  if (stored.inputType === live.inputType) score += 15

  // autocomplete (15 pts) — semantic, stable
  maxScore += 15
  if (stored.autocomplete && stored.autocomplete === live.autocomplete) score += 15
  else if (!stored.autocomplete && !live.autocomplete) score += 5

  // ariaLabel (10 pts)
  maxScore += 10
  if (stored.ariaLabel && stored.ariaLabel === live.ariaLabel) score += 10

  // placeholder (10 pts)
  maxScore += 10
  if (stored.placeholder && stored.placeholder === live.placeholder) score += 10
  else if (!stored.placeholder && !live.placeholder) score += 3

  // formActionHash (10 pts) — form action is fairly stable
  maxScore += 10
  if (stored.formActionHash && stored.formActionHash === live.formActionHash) score += 10
  else if (!stored.formActionHash && !live.formActionHash) score += 5

  // formDepth (5 pts) — structural hint
  maxScore += 5
  if (stored.formDepth === live.formDepth) score += 5

  // formIndex (5 pts) — position in form
  maxScore += 5
  if (stored.formIndex === live.formIndex) score += 5

  // inputMode (5 pts)
  maxScore += 5
  if (stored.inputMode === live.inputMode) score += 5

  return maxScore > 0 ? Math.round((score / maxScore) * 100) : 0
}

// ============================================================================
// §5  Helpers
// ============================================================================

/** Get the effective origin (scheme+host+port). */
export function effectiveOrigin(): string {
  return window.location.origin
}

/** Check if an element is visible, enabled, and connected. */
function isElementUsable(el: HTMLElement): boolean {
  if (!el.isConnected) return false
  const rect = el.getBoundingClientRect()
  if (rect.width === 0 && rect.height === 0) return false
  if ((el as HTMLInputElement).disabled) return false
  if (el.getAttribute('aria-hidden') === 'true') return false
  const style = getComputedStyle(el)
  if (style.display === 'none' || style.visibility === 'hidden') return false
  return true
}

/** Check if element is inside a cross-origin iframe. */
function isInCrossOriginFrame(el: HTMLElement): boolean {
  try {
    const win = el.ownerDocument?.defaultView
    if (!win) return true
    const _origin = win.location.origin
    return false
  } catch {
    return true
  }
}

/** CSS.escape with fallback for environments where it's unavailable (e.g. JSDOM). */
function cssEscape(value: string): string {
  if (typeof CSS !== 'undefined' && typeof CSS.escape === 'function') {
    return CSS.escape(value)
  }
  // Basic fallback: escape special CSS selector characters
  return value.replace(/([!"#$%&'()*+,./:;<=>?@[\\\]^`{|}~])/g, '\\$1')
}

/** Detect auto-generated IDs/names (contain random hex, long random strings). */
function looksAutoGenerated(value: string): boolean {
  if (value.length > 40) return true
  // Contains hex sequences typical of React/Angular auto-IDs
  if (/[0-9a-f]{8,}/i.test(value) && !/password|email|user|login|submit/i.test(value)) return true
  // Pure numeric or very short generic names are OK
  return false
}

/** Hash form action to hostname+path (no query, no fragment). Deterministic. */
function hashFormAction(action: string): string {
  try {
    const url = new URL(action, window.location.origin)
    const str = url.hostname + url.pathname
    // Simple DJB2 hash
    let h = 5381
    for (let i = 0; i < str.length; i++) {
      h = ((h << 5) + h + str.charCodeAt(i)) >>> 0
    }
    return h.toString(36)
  } catch {
    return ''
  }
}

/** Compute depth from form root (or document.body). */
function computeFormDepth(el: HTMLElement, form: HTMLFormElement | null): number {
  let depth = 0
  let current: HTMLElement | null = el
  const root = form ?? document.body
  while (current && current !== root && depth < 20) {
    current = current.parentElement
    depth++
  }
  return depth
}

/** Compute ordinal index among same-tagName siblings inside form. */
function computeFormIndex(el: HTMLElement, form: HTMLFormElement | null): number {
  const root = form ?? document.body
  const tag = el.tagName.toLowerCase()
  const siblings = root.querySelectorAll<HTMLElement>(tag)
  const list = Array.from(siblings)
  const idx = list.indexOf(el)
  return idx >= 0 ? idx : -1
}
