/**
 * BEAP Reply AI Provider
 *
 * Adapter that wires the existing LLM infrastructure (Ollama /api/llm/chat or
 * handshakeView.chatWithContextRag) into the AIProvider interface expected by
 * useReplyComposer.generateAiDraft.
 *
 * For draft generation, the classify() method sends the prompt to the LLM and
 * returns the response as suggestedAction (the draft text).
 */

import type { AIProvider, ProjectedContent, ClassificationContext, AiClassificationResponse } from './beapClassificationEngine'
import type { UrgencyLevel } from '../beapInboxTypes'

const PROVIDER_ID = 'beap-reply-draft'

/** Call the LLM to generate text. Returns the model's response or throws. */
export type LlmGenerateFn = (prompt: string) => Promise<string>

/**
 * Create an AIProvider that uses the given LLM function for draft generation.
 * The classify() method sends projectedContent.text to the LLM and returns
 * the response as suggestedAction (used by useReplyComposer as the draft).
 */
export function createBeapReplyAiProvider(generate: LlmGenerateFn): AIProvider {
  return {
    providerId: PROVIDER_ID,
    async classify(
      _messageId: string,
      projectedContent: ProjectedContent,
      _context: ClassificationContext,
    ): Promise<AiClassificationResponse> {
      const prompt = projectedContent.text?.trim() || ''
      if (!prompt) {
        return {
          urgency: 'normal' as UrgencyLevel,
          summary: '',
          suggestedAction: '',
          confidence: 0,
          reasoning: 'Empty prompt',
        }
      }
      const draft = await generate(prompt)
      return {
        urgency: 'normal' as UrgencyLevel,
        summary: '',
        suggestedAction: draft?.trim() || '',
        confidence: 0.9,
        reasoning: 'Draft generated by LLM',
      }
    },
  }
}
