/**
 * BEAP Reply AI Provider
 *
 * Adapter that wires the existing LLM infrastructure (Ollama /api/llm/chat or
 * handshakeView.chatWithContextRag) into the AIProvider interface expected by
 * useReplyComposer.generateAiDraft and useBulkClassification.
 *
 * Two modes:
 * 1. Draft generation: useReplyComposer passes "Draft a concise...\n\n---\n{content}".
 *    The provider sends the prompt to the LLM and returns the response as suggestedAction.
 * 2. Classification: useBulkClassification passes raw message content.
 *    The provider sends a classification prompt, parses the response, and returns
 *    { urgency, summary, suggestedAction, confidence }.
 */

import type { AIProvider, ProjectedContent, ClassificationContext, AiClassificationResponse } from './beapClassificationEngine'
import type { UrgencyLevel } from '../beapInboxTypes'

const PROVIDER_ID = 'beap-reply-draft'

const VALID_URGENCY: UrgencyLevel[] = ['urgent', 'action-required', 'normal', 'irrelevant']

/** Call the LLM to generate text. Returns the model's response or throws. */
export type LlmGenerateFn = (prompt: string) => Promise<string>

/**
 * Parse LLM classification response. Handles JSON or free-text with regex fallback.
 */
function parseClassificationResponse(raw: string): Partial<AiClassificationResponse> {
  const trimmed = raw?.trim() || ''
  if (!trimmed) return {}

  // Try JSON parse first
  const jsonMatch = trimmed.match(/\{[\s\S]*\}/)
  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch[0]) as Record<string, unknown>
      const urgency = typeof parsed.urgency === 'string' && VALID_URGENCY.includes(parsed.urgency as UrgencyLevel)
        ? (parsed.urgency as UrgencyLevel)
        : undefined
      const summary = typeof parsed.summary === 'string' ? parsed.summary : ''
      const suggestedAction = typeof parsed.suggestedAction === 'string' ? parsed.suggestedAction : ''
      const confidence = typeof parsed.confidence === 'number' ? parsed.confidence : 0.7
      return { urgency, summary, suggestedAction, confidence }
    } catch {
      /* fall through to regex */
    }
  }

  // Regex fallback: urgency keywords
  const lower = trimmed.toLowerCase()
  if (/\burgent\b/i.test(lower) || /\bcritical\b/i.test(lower) || /\bemergency\b/i.test(lower)) {
    return { urgency: 'urgent', summary: trimmed.slice(0, 120), confidence: 0.7 }
  }
  if (/\baction-required\b|\bactionrequired\b|\baction\s+required\b/i.test(lower)) {
    return { urgency: 'action-required', summary: trimmed.slice(0, 120), confidence: 0.7 }
  }
  if (/\birrelevant\b/i.test(lower) || /\bnewsletter\b/i.test(lower) || /\bmarketing\b/i.test(lower)) {
    return { urgency: 'irrelevant', summary: trimmed.slice(0, 120), confidence: 0.7 }
  }

  return { urgency: 'normal' as UrgencyLevel, summary: trimmed.slice(0, 120), confidence: 0.6 }
}

/**
 * Create an AIProvider that uses the given LLM function for draft generation
 * and classification.
 */
export function createBeapReplyAiProvider(generate: LlmGenerateFn): AIProvider {
  return {
    providerId: PROVIDER_ID,
    async classify(
      _messageId: string,
      projectedContent: ProjectedContent,
      _context: ClassificationContext,
    ): Promise<AiClassificationResponse> {
      const prompt = projectedContent.text?.trim() || ''
      if (!prompt) {
        return {
          urgency: 'normal' as UrgencyLevel,
          summary: '',
          suggestedAction: '',
          confidence: 0,
          reasoning: 'Empty prompt',
        }
      }

      // Draft mode: prompt starts with draft instruction
      const isDraftRequest = /^Draft a concise/i.test(prompt)
      if (isDraftRequest) {
        const draft = await generate(prompt)
        return {
          urgency: 'normal' as UrgencyLevel,
          summary: '',
          suggestedAction: draft?.trim() || '',
          confidence: 0.9,
          reasoning: 'Draft generated by LLM',
        }
      }

      // Classification mode: send classification prompt and parse response
      const classificationPrompt = `Classify this message. Return JSON only: { "urgency": "urgent"|"action-required"|"normal"|"irrelevant", "summary": "brief summary", "suggestedAction": "short action", "confidence": 0.0-1.0 }

Message:
${prompt}`
      try {
        const raw = await generate(classificationPrompt)
        const parsed = parseClassificationResponse(raw)
        return {
          urgency: (parsed.urgency ?? 'normal') as UrgencyLevel,
          summary: parsed.summary ?? '',
          suggestedAction: parsed.suggestedAction ?? '',
          confidence: parsed.confidence ?? 0.6,
          reasoning: parsed.reasoning ?? 'LLM classification',
        }
      } catch (err) {
        throw err
      }
    },
  }
}
